language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - composer dumpautoload

script:
  - vendor/bin/phpunit
